package targetdb

import (
	"errors"
	"strings"
	"testing"

	"pgloader-go/internal/catalog"
)

func TestRenderCreateTableIncludesIdentityDefaultsAndPrimaryKey(t *testing.T) {
	table := &catalog.Table{
		Schema: "dbo",
		Name:   "users",
		Columns: []*catalog.Column{
			{Name: "id", TargetType: "bigint", Identity: true},
			{Name: "email", TargetType: "text", Nullable: false},
			{Name: "external_id", TargetType: "uuid", Nullable: false, Default: "gen_random_uuid()"},
		},
		PrimaryKey: []string{"id"},
	}

	statement := renderCreateTable(table)

	checks := []string{
		`CREATE TABLE IF NOT EXISTS "dbo"."users"`,
		`"id" bigint GENERATED BY DEFAULT AS IDENTITY`,
		`"email" text NOT NULL`,
		`"external_id" uuid NOT NULL DEFAULT gen_random_uuid()`,
		`PRIMARY KEY ("id")`,
	}

	for _, check := range checks {
		if !strings.Contains(statement, check) {
			t.Fatalf("statement %q does not contain %q", statement, check)
		}
	}
}

func TestRenderCreateViewRejectsUnsupportedTSQL(t *testing.T) {
	view := &catalog.View{
		Schema:     "reporting",
		Name:       "latest_user",
		Definition: `CREATE VIEW reporting.latest_user AS SELECT TOP (1) id FROM dbo.users ORDER BY id DESC`,
	}

	_, err := renderCreateView(view)
	if !errors.Is(err, errUnsupportedViewDefinition) {
		t.Fatalf("renderCreateView error = %v, want unsupported view definition", err)
	}
	if err == nil || !strings.Contains(err.Error(), `TOP `) {
		t.Fatalf("renderCreateView error = %v, want message mentioning TOP", err)
	}
}

func TestRenderCreateIndexIncludesUniquenessAndColumns(t *testing.T) {
	table := &catalog.Table{Schema: "dbo", Name: "users"}
	index := &catalog.Index{Name: "idx_users_email", Unique: true, Columns: []string{"email", "city"}}

	statement := renderCreateIndex(table, index)
	want := `CREATE UNIQUE INDEX IF NOT EXISTS "idx_users_email" ON "dbo"."users" ("email", "city")`
	if statement != want {
		t.Fatalf("renderCreateIndex() = %q, want %q", statement, want)
	}
}

func TestRenderCreateIndexSupportsIncludeAndPredicate(t *testing.T) {
	table := &catalog.Table{Schema: "dbo", Name: "users"}
	index := &catalog.Index{
		Name:            "idx_users_name_filtered",
		Columns:         []string{"name"},
		IncludedColumns: []string{"city"},
		Predicate:       `[city] IS NOT NULL`,
	}

	statement := renderCreateIndex(table, index)
	want := `CREATE INDEX IF NOT EXISTS "idx_users_name_filtered" ON "dbo"."users" ("name") INCLUDE ("city") WHERE "city" IS NOT NULL`
	if statement != want {
		t.Fatalf("renderCreateIndex() = %q, want %q", statement, want)
	}
}

func TestRenderCreateForeignKeyIncludesActions(t *testing.T) {
	table := &catalog.Table{Schema: "sales", Name: "orders"}
	foreignKey := &catalog.ForeignKey{
		Name:              "fk_orders_user_id",
		Columns:           []string{"user_id"},
		ReferencedSchema:  "dbo",
		ReferencedTable:   "users",
		ReferencedColumns: []string{"id"},
		UpdateRule:        "NO ACTION",
		DeleteRule:        "CASCADE",
	}

	statement := renderCreateForeignKey(table, foreignKey)
	want := `ALTER TABLE "sales"."orders" ADD CONSTRAINT "fk_orders_user_id" FOREIGN KEY ("user_id") REFERENCES "dbo"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE`
	if statement != want {
		t.Fatalf("renderCreateForeignKey() = %q, want %q", statement, want)
	}
}

func TestRenderCreateForeignKeySupportsCompositeColumns(t *testing.T) {
	table := &catalog.Table{Schema: "sales", Name: "order_regions"}
	foreignKey := &catalog.ForeignKey{
		Name:              "fk_order_regions_user_region",
		Columns:           []string{"user_id", "region_code"},
		ReferencedSchema:  "sales",
		ReferencedTable:   "user_regions",
		ReferencedColumns: []string{"user_id", "region_code"},
		UpdateRule:        "CASCADE",
		DeleteRule:        "NO ACTION",
	}

	statement := renderCreateForeignKey(table, foreignKey)
	want := `ALTER TABLE "sales"."order_regions" ADD CONSTRAINT "fk_order_regions_user_region" FOREIGN KEY ("user_id", "region_code") REFERENCES "sales"."user_regions" ("user_id", "region_code") ON UPDATE CASCADE ON DELETE NO ACTION`
	if statement != want {
		t.Fatalf("renderCreateForeignKey() = %q, want %q", statement, want)
	}
}

func TestRenderCreateViewNormalizesCommonTSQL(t *testing.T) {
	view := &catalog.View{
		Schema:     "reporting",
		Name:       "user_labels",
		Definition: "SET ANSI_NULLS ON\nGO\nSET QUOTED_IDENTIFIER ON\nGO\nCREATE VIEW [reporting].[user_labels] AS\nSELECT [u].[id], ISNULL([u].[city], N'unknown') AS [city_label], GETDATE() AS [generated_at]\nFROM [dbo].[users] AS [u]",
	}

	statement, err := renderCreateView(view)
	if err != nil {
		t.Fatalf("renderCreateView returned error: %v", err)
	}

	wants := []string{
		`CREATE OR REPLACE VIEW "reporting"."user_labels" AS`,
		`COALESCE("u"."city", 'unknown') AS "city_label"`,
		`CURRENT_TIMESTAMP AS "generated_at"`,
		`FROM "dbo"."users" AS "u"`,
	}
	for _, want := range wants {
		if !strings.Contains(statement, want) {
			t.Fatalf("statement %q does not contain %q", statement, want)
		}
	}
}

func TestRenderCreateViewNormalizesAdditionalTSQLFunctions(t *testing.T) {
	view := &catalog.View{
		Schema:     "reporting",
		Name:       "user_metrics",
		Definition: `CREATE VIEW [reporting].[user_metrics] AS SELECT LEN([u].[name]) AS [name_len], DATALENGTH([u].[name]) AS [name_bytes], GETUTCDATE() AS [generated_utc] FROM [dbo].[users] AS [u]`,
	}

	statement, err := renderCreateView(view)
	if err != nil {
		t.Fatalf("renderCreateView returned error: %v", err)
	}

	wants := []string{
		`LENGTH("u"."name") AS "name_len"`,
		`OCTET_LENGTH("u"."name") AS "name_bytes"`,
		`(CURRENT_TIMESTAMP AT TIME ZONE 'UTC') AS "generated_utc"`,
	}
	for _, want := range wants {
		if !strings.Contains(statement, want) {
			t.Fatalf("statement %q does not contain %q", statement, want)
		}
	}
}
