package targetdb

import (
	"errors"
	"strings"
	"testing"

	"ms2pg/internal/catalog"
)

func TestRenderCreateTableIncludesIdentityDefaultsAndPrimaryKey(t *testing.T) {
	table := &catalog.Table{
		Schema: "dbo",
		Name:   "users",
		Columns: []*catalog.Column{
			{Name: "id", TargetType: "bigint", Identity: true},
			{Name: "email", TargetType: "text", Nullable: false},
			{Name: "external_id", TargetType: "uuid", Nullable: false},
		},
		PrimaryKey: []string{"id"},
	}

	statement := renderCreateTable(table)

	checks := []string{
		`CREATE TABLE IF NOT EXISTS "dbo"."users"`,
		`"id" bigint GENERATED BY DEFAULT AS IDENTITY`,
		`"email" text NOT NULL`,
		`"external_id" uuid NOT NULL`,
		`PRIMARY KEY ("id")`,
	}

	for _, check := range checks {
		if !strings.Contains(statement, check) {
			t.Fatalf("statement %q does not contain %q", statement, check)
		}
	}
}

func TestRenderCreateDefaultConstraint(t *testing.T) {
	table := &catalog.Table{Schema: "dbo", Name: "users"}
	defaultConstraint := &catalog.DefaultConstraint{
		Name:       "df_users_external_id",
		Column:     "external_id",
		Definition: "gen_random_uuid()",
	}

	statement, err := renderCreateDefaultConstraint(table, defaultConstraint)
	if err != nil {
		t.Fatalf("renderCreateDefaultConstraint returned error: %v", err)
	}
	want := `ALTER TABLE "dbo"."users" ALTER COLUMN "external_id" SET DEFAULT gen_random_uuid()`
	if statement != want {
		t.Fatalf("renderCreateDefaultConstraint() = %q, want %q", statement, want)
	}
}

func TestRenderCreateDefaultConstraintTranslatesConvert(t *testing.T) {
	table := &catalog.Table{Schema: "dbo", Name: "users"}
	defaultConstraint := &catalog.DefaultConstraint{
		Name:       "df_users_city_convert",
		Column:     "city",
		Definition: `CONVERT(nvarchar(100), 'London')`,
	}

	statement, err := renderCreateDefaultConstraint(table, defaultConstraint)
	if err != nil {
		t.Fatalf("renderCreateDefaultConstraint returned error: %v", err)
	}
	want := `ALTER TABLE "dbo"."users" ALTER COLUMN "city" SET DEFAULT ('London')::text`
	if statement != want {
		t.Fatalf("renderCreateDefaultConstraint() = %q, want %q", statement, want)
	}
}

func TestRenderCreateDefaultConstraintRejectsTryConvert(t *testing.T) {
	table := &catalog.Table{Schema: "dbo", Name: "users"}
	defaultConstraint := &catalog.DefaultConstraint{
		Name:       "df_users_city_try",
		Column:     "city",
		Definition: `TRY_CONVERT(nvarchar(100), city)`,
	}

	_, err := renderCreateDefaultConstraint(table, defaultConstraint)
	if !errors.Is(err, errUnsupportedDefaultConstraintDefinition) {
		t.Fatalf("renderCreateDefaultConstraint error = %v, want unsupported default constraint definition", err)
	}
	if err == nil || !strings.Contains(err.Error(), `TRY_CONVERT(`) {
		t.Fatalf("renderCreateDefaultConstraint error = %v, want message mentioning TRY_CONVERT", err)
	}
}

func TestRenderCreateViewRejectsUnsupportedTSQL(t *testing.T) {
	view := &catalog.View{
		Schema:     "reporting",
		Name:       "latest_user",
		Definition: `CREATE VIEW reporting.latest_user AS SELECT TOP (1) id FROM dbo.users ORDER BY id DESC`,
	}

	_, err := renderCreateView(view)
	if !errors.Is(err, errUnsupportedViewDefinition) {
		t.Fatalf("renderCreateView error = %v, want unsupported view definition", err)
	}
	if err == nil || !strings.Contains(err.Error(), `TOP `) {
		t.Fatalf("renderCreateView error = %v, want message mentioning TOP", err)
	}
}

func TestRenderCreateIndexIncludesUniquenessAndColumns(t *testing.T) {
	table := &catalog.Table{Schema: "dbo", Name: "users"}
	index := &catalog.Index{Name: "idx_users_email", Unique: true, Columns: []string{"email", "city"}}

	statement := renderCreateIndex(table, index)
	want := `CREATE UNIQUE INDEX IF NOT EXISTS "idx_users_email" ON "dbo"."users" ("email", "city")`
	if statement != want {
		t.Fatalf("renderCreateIndex() = %q, want %q", statement, want)
	}
}

func TestRenderCreateIndexSupportsIncludeAndPredicate(t *testing.T) {
	table := &catalog.Table{Schema: "dbo", Name: "users"}
	index := &catalog.Index{
		Name:            "idx_users_name_filtered",
		Columns:         []string{"name"},
		IncludedColumns: []string{"city"},
		Predicate:       `[city] IS NOT NULL`,
	}

	statement := renderCreateIndex(table, index)
	want := `CREATE INDEX IF NOT EXISTS "idx_users_name_filtered" ON "dbo"."users" ("name") INCLUDE ("city") WHERE "city" IS NOT NULL`
	if statement != want {
		t.Fatalf("renderCreateIndex() = %q, want %q", statement, want)
	}
}

func TestRenderCreateIndexTranslatesIIFPredicate(t *testing.T) {
	table := &catalog.Table{Schema: "dbo", Name: "users"}
	index := &catalog.Index{
		Name:      "idx_users_city_present",
		Columns:   []string{"name"},
		Predicate: `IIF([city] IS NULL, 0, 1) = 1`,
	}

	want := `CREATE INDEX IF NOT EXISTS "idx_users_city_present" ON "dbo"."users" ("name") WHERE CASE WHEN "city" IS NULL THEN 0 ELSE 1 END = 1`
	statement := renderCreateIndex(table, index)
	if statement != want {
		t.Fatalf("renderCreateIndex() = %q, want %q", statement, want)
	}
}

func TestRenderCreateIndexTranslatesCastPredicateType(t *testing.T) {
	table := &catalog.Table{Schema: "dbo", Name: "users"}
	index := &catalog.Index{
		Name:      "idx_users_city_cast",
		Columns:   []string{"name"},
		Predicate: `city = CAST(N'London' AS nvarchar(100))`,
	}

	want := `CREATE INDEX IF NOT EXISTS "idx_users_city_cast" ON "dbo"."users" ("name") WHERE city = CAST('London' AS text)`
	if got := renderCreateIndex(table, index); got != want {
		t.Fatalf("renderCreateIndex() = %q, want %q", got, want)
	}
}

func TestRenderCreateForeignKeyIncludesActions(t *testing.T) {
	table := &catalog.Table{Schema: "sales", Name: "orders"}
	foreignKey := &catalog.ForeignKey{
		Name:              "fk_orders_user_id",
		Columns:           []string{"user_id"},
		ReferencedSchema:  "dbo",
		ReferencedTable:   "users",
		ReferencedColumns: []string{"id"},
		UpdateRule:        "NO ACTION",
		DeleteRule:        "CASCADE",
	}

	statement := renderCreateForeignKey(table, foreignKey)
	want := `ALTER TABLE "sales"."orders" ADD CONSTRAINT "fk_orders_user_id" FOREIGN KEY ("user_id") REFERENCES "dbo"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE`
	if statement != want {
		t.Fatalf("renderCreateForeignKey() = %q, want %q", statement, want)
	}
}

func TestRenderCreateForeignKeySupportsCompositeColumns(t *testing.T) {
	table := &catalog.Table{Schema: "sales", Name: "order_regions"}
	foreignKey := &catalog.ForeignKey{
		Name:              "fk_order_regions_user_region",
		Columns:           []string{"user_id", "region_code"},
		ReferencedSchema:  "sales",
		ReferencedTable:   "user_regions",
		ReferencedColumns: []string{"user_id", "region_code"},
		UpdateRule:        "CASCADE",
		DeleteRule:        "NO ACTION",
	}

	statement := renderCreateForeignKey(table, foreignKey)
	want := `ALTER TABLE "sales"."order_regions" ADD CONSTRAINT "fk_order_regions_user_region" FOREIGN KEY ("user_id", "region_code") REFERENCES "sales"."user_regions" ("user_id", "region_code") ON UPDATE CASCADE ON DELETE NO ACTION`
	if statement != want {
		t.Fatalf("renderCreateForeignKey() = %q, want %q", statement, want)
	}
}

func TestRenderCreateUniqueConstraintSupportsCompositeColumns(t *testing.T) {
	table := &catalog.Table{Schema: "sales", Name: "user_regions"}
	uniqueConstraint := &catalog.UniqueConstraint{
		Name:    "uq_user_regions_label_region",
		Columns: []string{"label", "region_code"},
	}

	statement, err := renderCreateUniqueConstraint(table, uniqueConstraint)
	if err != nil {
		t.Fatalf("renderCreateUniqueConstraint returned error: %v", err)
	}
	want := `ALTER TABLE "sales"."user_regions" ADD CONSTRAINT "uq_user_regions_label_region" UNIQUE ("label", "region_code")`
	if statement != want {
		t.Fatalf("renderCreateUniqueConstraint() = %q, want %q", statement, want)
	}
}

func TestRenderCreateUniqueConstraintRejectsEmptyColumns(t *testing.T) {
	table := &catalog.Table{Schema: "dbo", Name: "users"}
	uniqueConstraint := &catalog.UniqueConstraint{Name: "uq_users_external_id"}

	_, err := renderCreateUniqueConstraint(table, uniqueConstraint)
	if !errors.Is(err, errInvalidUniqueConstraint) {
		t.Fatalf("renderCreateUniqueConstraint error = %v, want invalid unique constraint metadata", err)
	}
	if err == nil || !strings.Contains(err.Error(), "no columns") {
		t.Fatalf("renderCreateUniqueConstraint error = %v, want message mentioning no columns", err)
	}
}

func TestRenderCreateCheckConstraintNormalizesDefinition(t *testing.T) {
	table := &catalog.Table{Schema: "dbo", Name: "users"}
	checkConstraint := &catalog.CheckConstraint{
		Name:       "ck_users_name_nonempty",
		Definition: `(LEN([name]) > 0 AND [name] <> N'')`,
	}

	statement, err := renderCreateCheckConstraint(table, checkConstraint)
	if err != nil {
		t.Fatalf("renderCreateCheckConstraint returned error: %v", err)
	}
	want := `ALTER TABLE "dbo"."users" ADD CONSTRAINT "ck_users_name_nonempty" CHECK ((LENGTH("name") > 0 AND "name" <> ''))`
	if statement != want {
		t.Fatalf("renderCreateCheckConstraint() = %q, want %q", statement, want)
	}
}

func TestRenderCreateCheckConstraintTranslatesConvert(t *testing.T) {
	table := &catalog.Table{Schema: "dbo", Name: "users"}
	checkConstraint := &catalog.CheckConstraint{
		Name:       "ck_users_city_convert",
		Definition: `(city = CONVERT(nvarchar(100), N'London'))`,
	}

	statement, err := renderCreateCheckConstraint(table, checkConstraint)
	if err != nil {
		t.Fatalf("renderCreateCheckConstraint returned error: %v", err)
	}
	want := `ALTER TABLE "dbo"."users" ADD CONSTRAINT "ck_users_city_convert" CHECK ((city = ('London')::text))`
	if statement != want {
		t.Fatalf("renderCreateCheckConstraint() = %q, want %q", statement, want)
	}
}

func TestRenderCreateCheckConstraintRejectsConvertWithStyleArg(t *testing.T) {
	table := &catalog.Table{Schema: "dbo", Name: "users"}
	checkConstraint := &catalog.CheckConstraint{
		Name:       "ck_users_created_style",
		Definition: `(CONVERT(varchar(10), created_at, 120) = '2024-01-01')`,
	}

	_, err := renderCreateCheckConstraint(table, checkConstraint)
	if !errors.Is(err, errUnsupportedCheckConstraintDefinition) {
		t.Fatalf("renderCreateCheckConstraint error = %v, want unsupported check constraint definition", err)
	}
}

func TestRenderCreateCheckConstraintAllowsTrimFunctions(t *testing.T) {
	table := &catalog.Table{Schema: "dbo", Name: "users"}
	checkConstraint := &catalog.CheckConstraint{
		Name:       "ck_users_city_trimmed",
		Definition: `(LTRIM(RTRIM([city])) <> N'')`,
	}

	statement, err := renderCreateCheckConstraint(table, checkConstraint)
	if err != nil {
		t.Fatalf("renderCreateCheckConstraint returned error: %v", err)
	}
	want := `ALTER TABLE "dbo"."users" ADD CONSTRAINT "ck_users_city_trimmed" CHECK ((LTRIM(RTRIM("city")) <> ''))`
	if statement != want {
		t.Fatalf("renderCreateCheckConstraint() = %q, want %q", statement, want)
	}
}

func TestRenderCreateViewNormalizesCommonTSQL(t *testing.T) {
	view := &catalog.View{
		Schema:     "reporting",
		Name:       "user_labels",
		Definition: "SET ANSI_NULLS ON\nGO\nSET QUOTED_IDENTIFIER ON\nGO\nCREATE VIEW [reporting].[user_labels] AS\nSELECT [u].[id], ISNULL([u].[city], N'unknown') AS [city_label], GETDATE() AS [generated_at]\nFROM [dbo].[users] AS [u]",
	}

	statement, err := renderCreateView(view)
	if err != nil {
		t.Fatalf("renderCreateView returned error: %v", err)
	}

	wants := []string{
		`CREATE OR REPLACE VIEW "reporting"."user_labels" AS`,
		`COALESCE("u"."city", 'unknown') AS "city_label"`,
		`CURRENT_TIMESTAMP AS "generated_at"`,
		`FROM "dbo"."users" AS "u"`,
	}
	for _, want := range wants {
		if !strings.Contains(statement, want) {
			t.Fatalf("statement %q does not contain %q", statement, want)
		}
	}
}

func TestRenderCreateViewNormalizesAdditionalTSQLFunctions(t *testing.T) {
	view := &catalog.View{
		Schema:     "reporting",
		Name:       "user_metrics",
		Definition: `CREATE VIEW [reporting].[user_metrics] AS SELECT LEN([u].[name]) AS [name_len], DATALENGTH([u].[name]) AS [name_bytes], GETUTCDATE() AS [generated_utc] FROM [dbo].[users] AS [u]`,
	}

	statement, err := renderCreateView(view)
	if err != nil {
		t.Fatalf("renderCreateView returned error: %v", err)
	}

	wants := []string{
		`LENGTH("u"."name") AS "name_len"`,
		`OCTET_LENGTH("u"."name") AS "name_bytes"`,
		`(CURRENT_TIMESTAMP AT TIME ZONE 'UTC') AS "generated_utc"`,
	}
	for _, want := range wants {
		if !strings.Contains(statement, want) {
			t.Fatalf("statement %q does not contain %q", statement, want)
		}
	}
}

func TestRenderCreateViewNormalizesCharIndex(t *testing.T) {
	view := &catalog.View{
		Schema:     "reporting",
		Name:       "user_positions",
		Definition: `CREATE VIEW [reporting].[user_positions] AS SELECT [u].[id], CHARINDEX(N'a', [u].[name]) AS [first_a] FROM [dbo].[users] AS [u]`,
	}

	statement, err := renderCreateView(view)
	if err != nil {
		t.Fatalf("renderCreateView returned error: %v", err)
	}

	if !strings.Contains(statement, `POSITION('a' IN "u"."name") AS "first_a"`) {
		t.Fatalf("statement %q does not contain translated CHARINDEX expression", statement)
	}
}

func TestRenderCreateViewNormalizesDateAddDay(t *testing.T) {
	view := &catalog.View{
		Schema:     "reporting",
		Name:       "user_schedule",
		Definition: `CREATE VIEW [reporting].[user_schedule] AS SELECT [u].[id], DATEADD(day, 1, [u].[created_at]) AS [created_plus_day] FROM [dbo].[users] AS [u]`,
	}

	statement, err := renderCreateView(view)
	if err != nil {
		t.Fatalf("renderCreateView returned error: %v", err)
	}

	if !strings.Contains(statement, `("u"."created_at" + (1 * INTERVAL '1 day')) AS "created_plus_day"`) {
		t.Fatalf("statement %q does not contain translated DATEADD expression", statement)
	}
}

func TestRenderCreateViewNormalizesDateDiffDay(t *testing.T) {
	view := &catalog.View{
		Schema:     "reporting",
		Name:       "user_day_span",
		Definition: `CREATE VIEW [reporting].[user_day_span] AS SELECT [u].[id], DATEDIFF(day, '2000-01-01', '2000-01-03') AS [day_span] FROM [dbo].[users] AS [u]`,
	}

	statement, err := renderCreateView(view)
	if err != nil {
		t.Fatalf("renderCreateView returned error: %v", err)
	}

	if !strings.Contains(statement, `(('2000-01-03')::date - ('2000-01-01')::date) AS "day_span"`) {
		t.Fatalf("statement %q does not contain translated DATEDIFF expression", statement)
	}
}

func TestNormalizeSQLExpressionTranslatesReplicate(t *testing.T) {
	input := `REPLICATE([sep], 3)`
	want := `REPEAT("sep", 3)`
	if got := normalizeSQLExpression(input); got != want {
		t.Fatalf("normalizeSQLExpression(%q) = %q, want %q", input, got, want)
	}
}

func TestNormalizeSQLExpressionTranslatesSpace(t *testing.T) {
	input := `SPACE(4)`
	want := `REPEAT(' ', 4)`
	if got := normalizeSQLExpression(input); got != want {
		t.Fatalf("normalizeSQLExpression(%q) = %q, want %q", input, got, want)
	}
}

func TestNormalizeSQLExpressionTranslatesConvertSimple(t *testing.T) {
	cases := []struct{ in, want string }{
		{`CONVERT(varchar, [col])`, `("col")::text`},
		{`CONVERT(int, [score])`, `("score")::integer`},
		{`CONVERT(bigint, [score])`, `("score")::bigint`},
		{`CONVERT(date, [created_at])`, `("created_at")::date`},
		{`CONVERT(datetime, [ts])`, `("ts")::timestamp`},
		{`CONVERT(float, [val])`, `("val")::double precision`},
		{`CONVERT(numeric(18,2), [amount])`, `("amount")::numeric`},
	}
	for _, tc := range cases {
		if got := normalizeSQLExpression(tc.in); got != tc.want {
			t.Errorf("normalizeSQLExpression(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestNormalizeSQLExpressionLeavesConvertWithStyleUntouched(t *testing.T) {
	// 3-arg CONVERT (with style) must not be translated.
	input := `CONVERT(varchar(10), created_at, 120)`
	if got := normalizeSQLExpression(input); got != input {
		t.Fatalf("normalizeSQLExpression(%q) = %q, want unchanged", input, got)
	}
}

func TestNormalizeSQLExpressionTranslatesLogSingleArg(t *testing.T) {
	// SQL Server LOG(x) = natural log; PG LOG(x) = base-10; must become LN(x).
	input := `LOG([val])`
	want := `LN("val")`
	if got := normalizeSQLExpression(input); got != want {
		t.Fatalf("normalizeSQLExpression(%q) = %q, want %q", input, got, want)
	}
}

func TestNormalizeSQLExpressionLeavesLogTwoArgUntouched(t *testing.T) {
	// LOG(x, base) has no direct PG equivalent; must remain for portability check to reject.
	input := `LOG(8.0, 2)`
	if got := normalizeSQLExpression(input); got != input {
		t.Fatalf("normalizeSQLExpression(%q) = %q, want unchanged", input, got)
	}
}

func TestNormalizeSQLExpressionCharIndexTwoArg(t *testing.T) {
	input := `CHARINDEX(N'x', [col])`
	want := `POSITION('x' IN "col")`
	if got := normalizeSQLExpression(input); got != want {
		t.Fatalf("normalizeSQLExpression(%q) = %q, want %q", input, got, want)
	}
}

func TestNormalizeSQLExpressionCharIndexThreeArgLeftUntranslated(t *testing.T) {
	// 3-arg CHARINDEX is not translated (portability check will reject it).
	input := `CHARINDEX('x', [col], 3)`
	got := normalizeSQLExpression(input)
	// Should NOT produce POSITION with invalid SQL — the 3-arg form must be left alone.
	if strings.Contains(got, "POSITION") {
		t.Fatalf("normalizeSQLExpression(%q) = %q, should not produce POSITION for 3-arg CHARINDEX", input, got)
	}
}

func TestNormalizeSQLExpressionDateAddColumnExpression(t *testing.T) {
	// DATEADD n parameter as a column reference must translate.
	input := `DATEADD(day, [offset_days], [created_at])`
	want := `("created_at" + ("offset_days" * INTERVAL '1 day'))`
	if got := normalizeSQLExpression(input); got != want {
		t.Fatalf("normalizeSQLExpression(%q) = %q, want %q", input, got, want)
	}
}

func TestNormalizeSQLExpressionDateDiffYear(t *testing.T) {
	input := `DATEDIFF(year, [hire_date], [termination_date])`
	want := `(EXTRACT(YEAR FROM ("termination_date")::date) - EXTRACT(YEAR FROM ("hire_date")::date))::integer`
	if got := normalizeSQLExpression(input); got != want {
		t.Fatalf("normalizeSQLExpression(%q) = %q, want %q", input, got, want)
	}
}

func TestNormalizeSQLExpressionDateDiffMonth(t *testing.T) {
	input := `DATEDIFF(month, [start_date], [end_date])`
	want := `((EXTRACT(YEAR FROM ("end_date")::date) - EXTRACT(YEAR FROM ("start_date")::date)) * 12 + (EXTRACT(MONTH FROM ("end_date")::date) - EXTRACT(MONTH FROM ("start_date")::date)))::integer`
	if got := normalizeSQLExpression(input); got != want {
		t.Fatalf("normalizeSQLExpression(%q) = %q, want %q", input, got, want)
	}
}

func TestNormalizeSQLExpressionDateDiffQuarter(t *testing.T) {
	input := `DATEDIFF(quarter, [start_date], [end_date])`
	want := `((EXTRACT(YEAR FROM ("end_date")::date) * 4 + EXTRACT(QUARTER FROM ("end_date")::date)) - (EXTRACT(YEAR FROM ("start_date")::date) * 4 + EXTRACT(QUARTER FROM ("start_date")::date)))::integer`
	if got := normalizeSQLExpression(input); got != want {
		t.Fatalf("normalizeSQLExpression(%q) = %q, want %q", input, got, want)
	}
}

func TestNormalizeSQLExpressionTranslatesCastMSSQLTypes(t *testing.T) {
	cases := []struct{ in, want string }{
		{`CAST([col] AS nvarchar)`, `CAST("col" AS text)`},
		{`CAST([col] AS nvarchar(50))`, `CAST("col" AS text)`},
		{`CAST([col] AS nvarchar(max))`, `CAST("col" AS text)`},
		{`CAST([ts] AS datetime)`, `CAST("ts" AS timestamp)`},
		{`CAST([ts] AS datetime2)`, `CAST("ts" AS timestamp)`},
		{`CAST([ts] AS datetimeoffset)`, `CAST("ts" AS timestamptz)`},
		{`CAST([id] AS uniqueidentifier)`, `CAST("id" AS uuid)`},
		{`CAST([n] AS tinyint)`, `CAST("n" AS smallint)`},
		{`CAST([b] AS bit)`, `CAST("b" AS boolean)`},
		{`CAST([amt] AS money)`, `CAST("amt" AS numeric)`},
		{`CAST([name] AS sysname)`, `CAST("name" AS text)`},
	}
	for _, tc := range cases {
		if got := normalizeSQLExpression(tc.in); got != tc.want {
			t.Errorf("normalizeSQLExpression(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestNormalizeSQLExpressionTranslatesNestedCast(t *testing.T) {
	input := `CAST(CAST([col] AS nvarchar) AS datetime)`
	want := `CAST(CAST("col" AS text) AS timestamp)`
	if got := normalizeSQLExpression(input); got != want {
		t.Fatalf("normalizeSQLExpression(%q) = %q, want %q", input, got, want)
	}
}
